{
  # Training cofiguration
  'dataset': autoregressive,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.1,
  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': buv,
  'num_frames': 6,   #number of frames per batch
  'selection': False,
  'clip': all,
  'dimension': swap,
  'model': siren2,
  'comment' : separate,
  'finetune': False,
  'sobel': False,
  'inner_lr': 0.1, 
  'guidance': False,
  'mode': separate,
   'in_size': 2,
   'out_size': 1,
   'data_type':img,


  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 256,
  'num_layers': 10,  #10
  'latent_modulation_dim': 512,  #4096
  'v_dim': 2048, #4096
  
 'load_path': ./logs/path_to_best.model, 

  # Save NFs to
  'save_dir': ./reconstructions/buv_ours/
}