{
  # Training cofiguration
  'dataset': echo_3d,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.2,
  'data_type': img3d,

  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': echo,
  'num_frames':  10,
  'clip': all,
  'in_size': 3, 
  'out_size' :  1,
  'dimension': 3d,
  'comment' : 3dplain, #additive_6_subsequent,
  'mode': plain,
  'model': siren,
  'finetune': False,
  'selection': False,
  'sobel': False,
  'inner_lr': 0.1, 
  'guidance': False,
  'adversarial': False,


  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 256,
  'num_layers': 10,  
  'latent_modulation_dim': 8192, 
  'v_dim': 0, 

 
 'load_path': ./logs/path_to_best.model, 

  # Save NFs to
 'save_dir': ./reconstructions/echo_3d/
}