{
  # Training cofiguration
  'dataset': framewise_echo,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.2,
  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': echo,
  'num_frames': 6,
  'clip': all,
  'in_size': 2, 
  'out_size' :  1,
  'data_type': img,
  'dimension': swap,
  'comment' : separate, #additive_6_subsequent,
  'mode': separate,
  'model': siren2,
  'finetune': False,
  'selection': False,
  'sobel': False,
  'inner_lr': 0.1, 
  'guidance': False,
  'adversarial': False,


  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 256,
  'num_layers': 10,  #10
  'latent_modulation_dim': 512,  #4096
  'v_dim': 2048, #4096

 #'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250523_framewise_echo_modelsiren2_numlayers10_optionecho_guidanceTrue_lam1e-05_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.15_hiddensize256_vdim2048_frames10_numlayers10_commentseparateguidedecho_framewise/step10000.model,
 #'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250521_framewise_echo_modelsiren_numlayers10_optionecho_guidanceFalse_lam0_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.2_hiddensize256_vdim0_frames6_numlayers10_commentplainecho_framewise/best.model,
#'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250523_framewise_echo_modelsiren2_numlayers10_optionecho_guidanceFalse_lam1000_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.15_hiddensize256_vdim2048_frames6_numlayers10_commentadversarialecho_framewise/best.model,
 #'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250524_framewise_echo_modelsiren2_numlayers10_optionecho_guidanceTrue_lam5e-06_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.15_hiddensize256_vdim2048_frames10_numlayers10_commentguidedecho_framewise/step60000.model,
#  'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250530_autoregressive_modelsiren2_numlayers10_optionmixed_guidanceFalse_lam0.0_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.2_hiddensize256_vdim2048_frames6_numlayers10_commentonlylungandbreastmixed/best.model,
#   'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250514_autoregressive_modelsiren2_numlayers10_optionmixed_guidanceFalse_lam0.0_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.2_hiddensize512_vdim2048_frames4_numlayers10_commentseparatemixed/best.model,
# 'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250603_framewise_echo_modelsiren2_numlayers10_optionecho_guidanceFalse_lam0.0_inner10_size112_innerlr0.1_meatlr3e-06_latentsize512_gamma0.2_hiddensize256_vdim2048_frames6_numlayers10_commentfinetune10echo_framewise/best.model,
'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250508_framewise_echo_modelsiren2_numlayers10_optionecho_inner10_size112_innerlr0.1_latentsize512_gamma0.2_hiddensize256_vdim2048_frames4_numlayers10_commentseparateecho_framewise/best.model,
  # Save NFs to
  'save_dir': ./reconstructions/echo_separate_512_allvideos/
}