{
  # Training cofiguration
  'dataset':  framewise_echo,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.2,
  'data_type': img,

  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': echo,
  'num_frames':  6,
  'clip': all,
  'in_size': 2, 
  'out_size' :  1,
  'dimension': swap,
  'comment' : spatial, #additive_6_subsequent,
  'mode': spatial,
  'model': siren2,
  'finetune': False,
  'selection': False,
  'sobel': False,
  'inner_lr': 0.1, 
  'guidance': False,
  'adversarial': False,
  'shape': 4464,



  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 10,

  # Model config
  'hidden_size': 256,
  'num_layers': 10,  #10
  'latent_modulation_dim': 64,  #4096
  'v_dim': 0, #4096

 
 'load_path': /gpfs/gibbs/project/hartley/jw3234/medfuncta/vidfuncta/logs/250609_framewise_echo_modelsiren2_numlayers10_optionecho_guidanceFalse_lam0.0_inner10_size112_innerlr0.1_meatlr3e-06_latentsize4464_gamma0.2_hiddensize256_vdim0_frames6_numlayers10_commentspatialecho_spatial/best.model,
 # Save NFs to
 'save_dir': ./reconstructions/echo_spatial_4464/
}