{
  # Training cofiguration
  'dataset':  autoregressive,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.2,
  'data_type': img,

  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': bedlus,
  'num_frames':  6,
  'clip': all,
  'in_size': 2, 
  'out_size' :  1,
  'dimension': swap,
  'comment' : spatial, 
  'mode': spatial,
  'model': siren2,
  'finetune': False,
  'selection': False,
  'sobel': False,
  'inner_lr': 0.1, 
  'guidance': False,
  'adversarial': False,
  'shape': 4464,
  'in_size': 2,
  'out_size': 1,
  'data_type': img,


  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 256,
  'num_layers': 10,  #10
  'latent_modulation_dim': 64, 
  'v_dim': 0, 

 
  'load_path': ./logs/path_to_best.model, 

 # Save NFs to
 'save_dir': ./reconstructions/lung_spatial_4464/
}