{
  # Training cofiguration
  'dataset': autoregressive,
  'img_size': 112,
  'batch_size': 1,
  'inner_steps': 10,
  'inner_steps_boot': 0,
  'data_ratio': 0.25,
  'sample_type': random,
  'lam': 0.0,
  'w0': 10.,
  'w0_increment': 5.,
  'option': mixed,
  'num_frames': 4,   #number of frames per batch
  'selection': False,
  'clip': all,
  'dimension': swap,
  'comment' :separate,
  'inner_lr': 0.1, 
  'mode': separate,
  'sobel': False,
  'guidance': False,
  'model': siren2,
  'finetune': False,
  'selection': False,
  'guidance': False,


  # Test configuration
  'test_batch_size': 1,
  'num_test_signals': 100,
  'inner_steps_test': 20,

  # Model config
  'hidden_size': 256, 
  'num_layers': 10,  
  'latent_modulation_dim':  512,  
  'v_dim': 2048,

 'load_path': ./logs/path_to_best.model, 

  
  # Save NFs to
  'save_dir':   ./reconstructions/mixed_ours/
}